steps:

- name: 'gcr.io/cloud-builders/docker'
  args: [ "login",
        "-u", "$_DOCKER_USERNAME",
        "-p", "$_DOCKER_PASSWORD",
  ]

- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - docker pull botfront/botfront-ce:latest || exit 0

- name: 'gcr.io/cloud-builders/docker'
  args: [ "build",
          "-t", "botfront/botfront-ce:$TAG_NAME",
          "-t", "botfront/botfront-ce:latest",
          "--cache-from", "botfront/botfront-ce:latest",
          "."]

- name: 'gcr.io/cloud-builders/docker'
  args: [ "push", "botfront/botfront-ce:$TAG_NAME"]

- name: 'gcr.io/cloud-builders/docker'
  args: [ "push", "botfront/botfront-ce:latest"]

timeout: 30m