steps:

- name: 'gcr.io/cloud-builders/docker'
  args: [ "login",
        "-u", "$_DOCKER_USERNAME",
        "-p", "$_DOCKER_PASSWORD",
  ]

- name: 'gcr.io/cloud-builders/docker'
  args: [ "build",
          "-t", "botfront/botfront:$TAG_NAME",
          "-t", "botfront/botfront:latest",
          "."]

- name: 'gcr.io/cloud-builders/docker'
  args: [ "push", "botfront/botfront:$TAG_NAME"]

- name: 'gcr.io/cloud-builders/docker'
  args: [ "push", "botfront/botfront:latest"]

timeout: 30m