steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    docker pull gcr.io/$PROJECT_ID/botfront-ee:latest || exit 0
- name: 'gcr.io/cloud-builders/docker'
  args: [ "build",
          "-t", "gcr.io/${PROJECT_ID}/botfront-ee:$TAG_NAME",
          "-t", "gcr.io/${PROJECT_ID}/botfront-ee:latest",
          "--cache-from", "gcr.io/$PROJECT_ID/botfront-ee:latest",
          "."]
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - set
  - image
  - deployment
  - botfront
  - botfront=gcr.io/${PROJECT_ID}/botfront-ee:$TAG_NAME
  - --namespace
  - ${_NAMESPACE}
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=${_COMPUTE_ZONE}'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_CONTAINER_CLUSTER}'

images:
- "gcr.io/${PROJECT_ID}/botfront-ee:latest"
- "gcr.io/${PROJECT_ID}/botfront-ee:$TAG_NAME"

timeout: 30m    