version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3333:3000'
    # links:
    #   - mongo
    environment:
      ROOT_URL: ${APP_ROOT_URL:-http://localhost}
      MONGO_URL: mongodb://docker.for.mac.host.internal:3001/meteor
      ADMIN_EMAIL: hello@mrbot.ai
      ADMIN_PW: aaaaaaaa
      PORT: 3000

  # mongo:
  #   image: mongo:latest
  #   command:
  #     - --storageEngine=wiredTiger
  #   volumes:
  #     - data:/data/db

volumes:
  data:
