credentials:
  rasa_addons.core.channels.webchat.WebchatInput:
    session_persistence: true
    base_url: https://{PROJECT_NAMESPACE}.{SOCKET_HOST}
    socket_path: /socket.io/
  rasa_addons.core.channels.bot_regression_test.BotRegressionTestInput: {}
instance: http://rasa-service.{PROJECT_NAMESPACE}
bfApiHost: http://botfront-api-service.botfront
endpoints:
  models:
    url: 'https://storage.googleapis.com/{GCP_MODELS_BUCKET}/model-{BF_PROJECT_ID}.tar.gz'
    wait_time_between_pulls: 3600
  nlg:
    type: rasa_addons.core.nlg.GraphQLNaturalLanguageGenerator
    url: http://botfront-app-service.botfront/graphql
  action_endpoint:
    url: http://actions-service.{PROJECT_NAMESPACE}/webhook
  tracker_store:
    store_type:  rasa_addons.core.tracker_stores.botfront.BotfrontTrackerStore
    url: http://botfront-app-service.botfront/graphql
policies:
  - name: TEDPolicy
    epochs: 50
    max_history: 5
    batch_size: [32, 64]
  - name: MemoizationPolicy
  - name: rasa_addons.core.policies.BotfrontDisambiguationPolicy
    fallback_trigger: 0.30
    disambiguation_trigger: '$0 < 2 * $1'
    disambiguation_template: 'utter_disambiguation'
    n_suggestions: 2
    excluded_intents:
      - ^chitchat\..*
      - ^basics\..*
defaultDomain:
  slots:
    disambiguation_message:
      type: unfeaturized
  actions:
    - action_botfront_disambiguation
    - action_botfront_disambiguation_followup
    - action_botfront_fallback
    - action_botfront_mapping
webhooks:
  restartRasaWebhook:
    name: RestartRasa
    url: ''
    method: POST
  uploadImageWebhook:
    name: UploadImage
    url: ''
    method: POST
  deleteImageWebhook:
    name: DeleteImage
    url: ''
    method: DELETE
  deploymentWebhook:
    name: DeployProject
    url: ''
    method: POST
  reportCrashWebhook:
    name: ReportCrash
    url: ''
    method: POST
