name: build

on:
  push:
    branches:
      - chrome-version

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Dump github context
        env:
          GH_CONTEXT: ${{ toJson(github) }}
        run: echo "$GH_CONTEXT"
      - name: peek chrome version
        run: google-chrome --version